### ISSUE TITLE
Point-and-click workflow tutorial outdated

### ISSUE THREAD

**Issue by jkotilahti** [iqm-finland/KQCircuits#11]
With new KLayout and KQCircuits versions some things have changed so that parts of ["point-and-click" workflow tutorial](https://iqm-finland.github.io/KQCircuits/user_guide/gui_workflow.html) don't work as described or are confusing. At least:

- Part 4.4-5.4: Not easy to select qubit because waveguide cells are selected instead.
	* Alternative way to select a qubit is to drag a selection box around it. Pressing "q" can then be used to open the "object properties" window.
- Part 6.5: The button is now a magnifying glass instead of "...".
	* Can mention both, so that both older and new KLayout versions can be used
- Part 7.1: Ground grid is not visible by default, should tell to unhide it in the layers list.

The end result should be such that everything works when following exactly the instructions in the tutorial.

**Comment by jkotilahti** [comment]
Hi @fred5825, feel free to ask questions here or https://github.com/iqm-finland/KQCircuits/discussions, or contact me in unitaryfund discord (same username).

**Comment by fred5825** [comment]
@jkotilahti Hi thank you I just sent you a discord invite.

**Comment by fred5825** [comment]
@jkotilahti please let me know if you have sometime to chat on discord.

**Comment by fred5825** [comment]
Hi I was wondering 
<img width="859" alt="Screen Shot 2022-06-11 at 12 12 23 AM" src="https://user-images.githubusercontent.com/101068945/173213831-1fdfa49c-b27a-4daf-9d9a-2d2a24241e53.png">
which one should I install for this issue

**Comment by fred5825** [comment]
Hi I was wondering which one should I install for this issue
<img width="859" alt="Screen Shot 2022-06-11 at 12 12 23 AM" src="https://user-images.githubusercontent.com/101068945/173213842-489eac0e-df0d-4272-b6ad-92d761b919bb.png">

Sorry formatting was wrong with the first one

**Comment by fred5825** [comment]
Hi for some reason I am unable to download the software this is the message that I get:
![Screen Shot 2022-06-13 at 1 18 27 AM](https://user-images.githubusercontent.com/101068945/173284772-78c74590-255e-4205-b520-ec220b14b00e.png)

**Comment by jkotilahti** [comment]
Hi @fred5825 

For installation I suggest using "developer setup" instead of "Salt package".

To run `klayout` on macOS despite that error message, the following should hopefully work:

![image](https://user-images.githubusercontent.com/83180458/173318951-daf76427-2256-43f3-b38b-1f864f6985be.png)

**Comment by fred5825** [comment]
Hi @jkotilahti I am trying to follow part 1.3 but the drag and drop does not work.
![Screen Shot 2022-06-14 at 4 55 28 PM](https://user-images.githubusercontent.com/101068945/173687359-b6453e76-c1aa-4ed2-a58e-8fe54a3639de.png)

**Comment by fred5825** [comment]
I don't know if its because I am on mac but a lot of the things mention are not part of my user interface

**Comment by fred5825** [comment]
But I went ahead and already correct the errors specified in the issue.

**Comment by jkotilahti** [comment]
Hi  @fred5825,

>I am trying to follow part 1.3 but the drag and drop does not work. 

Did you make sure you are running KLayout in "edit mode" as described in part 1.1 of the tutorial? If not, then the drag and drop won't work. If you are running KLayout in edit mode and it still doesn't work, could you describe in more detail what happens when you try to drag-and-drop?

>I don't know if its because I am on mac but a lot of the things mention are not part of my user interface

Some of them could be because of changes in new KLayout versions, so it's good if you modify the tutorial to explain also how it works for you :) We can check in the review if they are only because of mac or not.

**Comment by fred5825** [comment]
Hi @jkotila I am trying to follow the instructions but I don't see a Set up in file
![Screen Shot 2022-06-15 at 7 32 29 PM](https://user-images.githubusercontent.com/101068945/173959676-76e82946-4494-4085-a0f1-813b8189997a.png)
hti

**Comment by fred5825** [comment]
@jkotilahti sorry about the formatting above but yeah for some reason I don't see the option Setup in file.

**Comment by jkotilahti** [comment]
Hi @fred5825, it sounds a bit strange that there is no "Setup" in "File" menu (in top menu of KLayout). Maybe you could check also other menus in KLayout top menu and see if you could find the "editing mode" option somewhere. (you could also show me some screenshot of the "File" menu and maybe some other menus in your KLayout, it could help to find it)   

But if you can't find this option from the KLayout application, then another way to change is to find the `klayoutrc` file. By default this file is in `~/.klayout`, but could be somewhere else depending on your setup. Then in this file, change the line `<edit-mode>false</edit-mode>` into `<edit-mode>true</edit-mode>`.

**Comment by fred5825** [comment]
<img width="834" alt="Screen Shot 2022-06-16 at 2 41 20 PM" src="https://user-images.githubusercontent.com/101068945/174142546-ca60aef9-949e-45b3-82e2-c65960bca25b.png">

**Comment by fred5825** [comment]
I found the edit mode its actually in the preferences tab on mac not file, I can change that too in the walkthrough

**Comment by fred5825** [comment]
@jkotilahti Hi I don't see partial in tools like part 3.4 says.

**Comment by fred5825** [comment]
@jkotilahti never mind I was looking at the wrong thing, sorry

**Comment by fred5825** [comment]
<img width="474" alt="Screen Shot 2022-06-16 at 7 09 48 PM" src="https://user-images.githubusercontent.com/101068945/174192827-db01f9cb-1961-41d1-b15c-a769237e6af3.png">

**Comment by fred5825** [comment]
@jkotilahti Hi I am at this step its part 6.6 but I don't see the option Swissmon I see other options but not that.

**Comment by jkotilahti** [comment]
Sounds good @fred5825. The reason why you couldn't find Swissmon is that it was moved from "Element Library" to "Qubit Library". So the part 6.4 should also be changed to have "Qubit Library" instead of "Element Library", then part 6.6 should also work.

**Comment by fred5825** [comment]
@jkotilahti it works I will recreate pull request right now.

**Comment by jkotilahti** [comment]
Great! We will probably review it next week.

**Comment by fred5825** [comment]
Hi @jkotilahti the account @Renaud2002 is still me, thats my personal account its where I want to make contributions and the pull request has been opened.

**Comment by fred5825** [comment]
@jkotilahti yeah please don't hesitate to let me know if there is any changes I need to add, thank you.
