### ISSUE TITLE
Macro for printing the refpoint hierarchy

### ISSUE THREAD

**Issue by jkotilahti** [iqm-finland/KQCircuits#13]
To help users get a better understanding of refpoints, we could have a KLayout macro that prints out a list of all refpoints in the layout. The output should be formatted so that the hierarchy of the refpoints/cells is clear. 

There is now a macro that prints the refpoints (https://github.com/iqm-finland/KQCircuits/blob/main/klayout_package/python/scripts/macros/measure/print_refpoints.lym), but their hierarchy could be shown in some way in the output.

See https://iqm-finland.github.io/KQCircuits/user_guide/python_workflow.html#refpoints for an explanation about refpoints.

**Comment by divshacker** [comment]
Hey, I am interested in working on this issue. May I know What is KLayout macro and how it prints list?
Thanks

**Comment by jkotilahti** [comment]
Hi @divshacker! You can find information about KLayout macros in KQCircuits documentation https://iqm-finland.github.io/KQCircuits/user_guide/macro_workflow.html and in KLayout documentation https://www.klayout.de/doc-qt5/about/macro_editor.html.

In KQCircuits we have for example the `selection_length` macro, which prints out lengths of waveguides to the macro editor console. If you have installed KQCircuits in KLayout, then you can find this macro in `kqcircuits_scripts/macros/measure` folder in `Python` tab of the KLayout macro editor window. If you drag-and-drop a WaveguideCoplanar element into the layout and select it, then running this macro will print out its length.

**Comment by LeonWubben** [comment]
The mentioned macro has now been adjusted to show the hierarchy. Including an option to only print the refpoints whose names or cell match a given regex and an option to only print those refpoints that are within a certain range of coordinates.
