### ISSUE TITLE
Document that parallelised add_chips cannot be used with static cells

### ISSUE THREAD

**Issue by nikosavola** [iqm-finland/KQCircuits#29]
It seems that parallelised `add_chips` cannot be used when adding static cells due to the implementation, for these cases one should use `add_chip` or `add_chips(..., threads=1)`. This should be documented in the docstrings as a note.

Alternatively, add logic to check if the given cell is static, and use `add_chip` in that case.

In any case, adding static cells is very fast so no harm done in losing that ability in `add_chips`.

**Comment by iqmtestd** [comment]
I believe this is solved at v4.6.14. There is no more `add_chips` but instead `add_chip` is capable of processing either one chip or multiple chips. In both cases the `chip` parameter may be either a class or a file name of a static cell. This is documented in `add_chip`'s docstring.
