### ISSUE TITLE
Pulling Singularity image and using `create_links.sh` requires manual `mkdir`

### ISSUE THREAD

**Issue by nikosavola** [iqm-finland/KQCircuits#30]
If one tries to use the Singularity image by pulling instead of building (to the correct `libexec` folder as in the documentation), the `create_links.sh` actually fails due to the `bin` folder not existing in a fresh repo.
https://github.com/iqm-finland/KQCircuits/blob/c24853ac5adabad2319bfd536fb695d9ef9cf036/singularity/create_links.sh#L3

#### Suggestion
`mkdir bin` if it does not exist yet in `create_links.sh`

**Comment by Yaraslaut** [comment]
This was fixed in https://github.com/iqm-finland/KQCircuits/pull/63
https://github.com/iqm-finland/KQCircuits/blob/685e7dbb969586428ea05ee86273935879054e6f/singularity/create_links.sh#L10
