### ISSUE TITLE
FlipChipConnectorRf inconsistent between round and square connector shape

### ISSUE THREAD

**Issue by qpavsmi** [iqm-finland/KQCircuits#56]
### Description

The geometry for `FlipChipConnectorRf` with `round_connector=True` and `round_connector=False` are not consistent:
- The port name is `f"{face_id}_port"` for round connector, but empty string for square connector.
- When using `n_center_bumps > 1` and `output_rotation != 180`, the geometry of top and bottom face do not overlap. Instead of rotating only the output, the whole shape is rotated. This was fixed for round connector already, but is not yet fixed for square connector:

![image](https://github.com/iqm-finland/KQCircuits/assets/109152229/8d427408-e21b-4623-b70c-b5ebe469af71)

## Acceptance criteria

* Fix the multi-bump output rotation geometry to match that of round_connector
* Change port names to `f"{face_id}_port"` in square connector. This might break some tests

**Comment by iqmtestd** [comment]
By now I think port names are  all right for the square connector too. 

![image](https://github.com/iqm-finland/KQCircuits/assets/83572540/32649494-86fc-4577-a357-afaa8354459b)
