### ISSUE TITLE
Changing PCell Parameters erases cells

### ISSUE THREAD

**Issue by pauljametsuria** [iqm-finland/KQCircuits#7]

**Comment by jheinsoo** [comment]
I wonder why did you delete the problem description in the message

> I created a new element and I can generate it in the GUI but everytime I try to update a parameter from the PCell Parameters tab the element gets deleted. Any idea how to fix this? I followed the structure of other elements in the library.

I think there is certain KLayout version which has a bug in GUI. Could you please tell us the 
* exact KLayout version, 
* the PCell, its parameter and 
* parameter value you used for testing?

Thank you for reporting the bug! 
Johannes

**Comment by pauljametsuria** [comment]
Hello,

Sorry about that, I thought it would remove the issue completely. I could fix it by myself shortly after I posted it. The issue was that a PCell parameter was defined as TypeList instead of TypeDouble.

My mistake! Sorry again!

Best regards,

Paul
________________________________

**Comment by jheinsoo** [comment]
Thank your trying out KQC and best of lack in your next tests!
